name: Run UnitTests
on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'ovos_listener/version.py'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'readme.md'
      - 'scripts/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'ovos_simple_listener/version.py'
      - 'requirements/**'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'readme.md'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9, '3.10' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev swig libssl-dev libpulse-dev portaudio19-dev
          python -m pip install build wheel
      - name: Install core repo
        run: |
          pip install .[extras,linux,onnx]
      - name: Install test dependencies
        run: |
          pip install -r requirements/tests.txt
      - name: Run unittests
        run: |
          pytest test/unittests
